# Generated by Django 4.2.16 on 2024-11-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название проекта')),
                ('version', models.CharField(max_length=15, verbose_name='версия')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('link_in_git', models.CharField(max_length=150, verbose_name='Ссылка на гит')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
