# Generated by Django 4.2.16 on 2024-11-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default_image.jpg', upload_to='image/%Y/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
